todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list_app.urls", namespace="todo_list")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list_app/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    UndoOrCompleteTaskView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag-delete"),
    path("undo_or_complete/<int:pk>/", UndoOrCompleteTaskView.as_view(), name="undo-or-complete"),
]

app_name = "todo_list"

todo_list_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "-created_datetime"]

    def __str__(self):
        return self.content

todo_list_app/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic, View
from .models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "todo_list/task_list.html"


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = "todo_list/task_form.html"
    fields = "__all__"
    success_url = reverse_lazy("todo_list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    template_name = "todo_list/task_form.html"
    fields = "__all__"
    success_url = reverse_lazy("todo_list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo_list/task_confirm_delete.html"
    success_url = reverse_lazy("todo_list:task-list")


class TagListView(generic.ListView):
    model = Tag
    template_name = "todo_list/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    template_name = "todo_list/tag_form.html"
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    template_name = "todo_list/tag_form.html"
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo_list/tag_confirm_delete.html"
    success_url = reverse_lazy("todo_list:tag-list")


class UndoOrCompleteTaskView(View):
    @staticmethod
    def post(request, pk):
        task = Task.objects.get(pk=pk)
        task.is_done = not task.is_done
        task.save()
        return HttpResponseRedirect(
            reverse_lazy("todo_list:task-list")
        )

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file  -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_list:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tag-list' %}">Tags</a></li>
</ul>

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>

{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} a tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary link-to-page d-inline">
      Create
    </a>
  </h1>

  {% if tag_list %}
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  {% for tag in tag_list %}
    <tr>
      <td>{{ tag.name }}</td>
      <td>
        <a class="btn btn-primary"
           href="{% url 'todo_list:tag-update' pk=tag.id %}">
          Update
        </a>
      </td>
      <td>
        <a class="btn btn-danger"
           href="{% url 'todo_list:tag-delete' pk=tag.id %}">
          Delete
        </a>
      </td>
    </tr>
  {% endfor %}

  </table>
  {% block pagination %}
    {% include 'includes/pagination.html' %}
  {% endblock %}
  {% else %}
    <p>There are no task types in the manager.</p>
{% endif %}

{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
  
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
          
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} a task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}

{% block content %}
  <style>
      .link-to-page {
          float: right;
          margin: 0 2px 0 2px;
      }
  </style>
  <h1>
    TODO list
    <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page d-inline">
      Create
    </a>
  </h1>

  {% if task_list %}
  {% for task in task_list %}
    <h4>
      <strong>
        {{ task.content }}
        {% if task.is_done %}
          <span style="color: green;">Done</span>
          <form method="post" action="{% url 'todo_list:undo-or-complete' pk=task.id %}" class="link-to-page">
            {% csrf_token %}
            <input type="hidden" name="pk" value="{{ task.id }}">
            <button type="submit" style="border: none; background: none; cursor: pointer;">
              <span style="color: red;">Undo</span>
            </button>
          </form>
        {% else %}
          <span style="color: red;">Not done</span>
          <form method="post" action="{% url 'todo_list:undo-or-complete' pk=task.id %}" class="link-to-page">
            {% csrf_token %}
            <input type="hidden" name="pk" value="{{ task.id }}">
            <button type="submit" style="border: none; background: none; cursor: pointer;">
              <span style="color: green;">Complete</span>
            </button>
          </form>
        {% endif %}
      </strong>
    </h4>
    <br>
    Created: {{ task.created_datetime }}
    {% if task.deadline %}
      Deadline: {{ task.deadline }}
    {% endif %}
    <br>
    <br>
    Tags:
    {% for tag in task.tags.all %}
      {{ tag }}
    {% endfor %}
    <a href="{% url 'todo_list:task-update' pk=task.id %}">
      Update
    </a>
    <a href="{% url 'todo_list:task-delete' pk=task.id %}">
      Delete
    </a>
    <hr>
  {% endfor %}
  {% block pagination %}
    {% include 'includes/pagination.html' %}
  {% endblock %}
  {% else %}
    <p>There are no tasks in the list.</p>
{% endif %}

{% endblock %}